### ISSUE TITLE
Question about passing parameters to self-signing-certificate function

### ISSUE THREAD

**Issue by rowild** [niksy/dotfiles#40] opened 2018-07-08 14:55 UTC
Thank you very much for your fantastic scripts!!!

I wanted to report that I get an error:
```
error on line 29 of temp.cnf
140735698617288:error:0E079065:configuration file routines:DEF_LOAD_BIO:missing equal sign:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.50.2/libressl/crypto/conf/conf_def.c:348:line 29
```

Any idea, why this could be?
I do not have a folder called BuildRoot nor is libressl installed (on my Mac 10.13)...

**Comment by rowild** [comment] 2018-07-08 16:18
It seems the regex
```
sed -i '' $'s/\[ v3_req \]/[ v3_req ]\\\n\\\nsubjectAltName = @alt_names/' temp.cnf
```
is not working as expected.

For a starter, I tried to add a `^` to that line:
```
sed -i '' $'s/^\[ v3_req \]/[ v3_req ]\\\n\\\nsubjectAltName = @alt_names/' temp.cnf
```
That reduces the problems a bit, but not totally...
I keep trying and report back.

**Comment by rowild** [comment] 2018-07-08 17:50
Using a manual line break in the second sed command will generate a clean result:
```
  sed -i '' 's/^\[ v3_req \]/&\
subjectAltName = @alt_names/' temp.cnf
```
("subjectAltName" has to be at the beginning of the new line!)

This looks like an ugly hack and I hope I (or somebody else) will find a better solution. But for the moment this works.

**Comment by niksy** [comment] 2019-06-05 07:37
@rowild thanks for using scripts! Unfortunately, I can’t reproduce your bug so I guess it’s something related to your system. I’ll close this issue since it seems that you’ve fixed it.

**Closed by niksy** 2019-06-05 07:37 UTC
